package com.learning.webatm.enums;

public enum TransactionType {

    TRANSACTION_DEPOSIT,
    TRANSACTION_WITHDRAW,
    TRANSACTION_CHECK_ACCOUNT_BALANCE,

    TRANSACTION_REFILL,
    TRANSACTION_CHECK_ATM_BALANCE,


}
